apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fullnameOverride | default .Chart.Name }}-deployment
  labels:
    app: nginx-vo2
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nginx-vo2
  template:
    metadata:
      labels:
        app: nginx-vo2
    spec:
      volumes:
        - name: shared-data
          emptyDir: {}
        - name: scripts
          configMap:
            name: {{ .Values.configMaps.scripts }}
            items:
            - key: app.py
              path: app.py
            - key: config.yaml
              path: config.yaml
            - key: td.json
              path: td.json
        - name: summit
          configMap:
            name: {{ .Values.configMaps.summit }}  # Direct reference to existing ConfigMap
            items:
            - key: summit
              path: summit
      containers:
        - name: wotpy
          image: {{ .Values.image.wotpy }}
          imagePullPolicy: Always
          volumeMounts:
            - name: scripts
              mountPath: /app.py
              subPath: app.py
            - name: scripts
              mountPath: /config.yaml
              subPath: config.yaml
            - name: scripts
              mountPath: /td.json
              subPath: td.json
            - name: shared-data
              mountPath: /pod-data
          ports:
            - containerPort: {{ .Values.ports.http }}
            - containerPort: {{ .Values.ports.catalogue }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.ports.catalogue }}
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
            - name: HOSTNAME
              value: vo2

        - name: cors-nginx
          image: {{ .Values.image.corsNginx }}
          resources: {{ toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: summit
              mountPath: /usr/share/nginx/html/summit
              subPath: summit
            - name: shared-data
              mountPath: /usr/share/nginx/html
          ports:
            - containerPort: {{ .Values.ports.nginx }}

        - name: rosbagsaver-summit
          image: {{ .Values.image.rosbagsaver }}
          imagePullPolicy: Always
          resources: {{ toYaml .Values.resources | nindent 12 }}
          env:
            - name: ROS_DOMAIN_ID
              value: "0"
          command:
            - /run_rosbagsaver_summit.sh
          volumeMounts:
            - name: shared-data
              mountPath: /pod-data

