apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress-vo2
  labels:
    name: nginx-ingress-vo2
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service-vo2
                port:
                  number: {{ .Values.ports.nginx }}

