apiVersion: v1
kind: Service
metadata:
  name: rosbagsaver-service-summit
spec:
  selector:
    app: rosbagsaver-summit
  ports:
    - protocol: TCP
      port: {{ .Values.ports.nginx }}
      targetPort: {{ .Values.ports.nginx }}

