apiVersion: v1
kind: Service
metadata:
  name: nginx-service-vo2
  labels:
    app: nginx-vo2
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: {{ .Values.ports.nginx }}
      targetPort: {{ .Values.ports.nginx }}
  selector:
    app: nginx-vo2

