fullnameOverride: cvo
replicaCount: 1
appName: cvo
image:
  repository: nepheleproject/vo-wot
  pullPolicy: Always
  tag: latest

service:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30987
      protocol: TCP
    - name: catalogue-port
      port: 9090
      targetPort: 9090
      nodePort: 30988
      protocol: TCP

readinessProbe:
  httpGet:
    path: /
    port: 9090
  initialDelaySeconds: 10
  periodSeconds: 10

env:
  HOSTNAME: cvo

volumes:
  scripts:
    configMapName: cvo-scripts
    items:
      - key: app.py
        path: app.py
      - key: config.yaml
        path: config.yaml
      - key: td.json
        path: td.json

