# ====================================
# vo1 Descriptor
# ====================================
name: vo1
type: VO
resourceType:
  specification: WoT
  version: 1.1
deploymentType: A
catalogue: 9090 
bindingNB:
  bindingModeNB: [H]
  hostname: vo1
  ports:
    httpPort: 8080
bindingSB:
  bindingModeSB: [Z]
#  securitySB:
#      securitySBMQTT:
#        securityScheme: basic
#        username: user
#        password: pass
  routerURL: "160.85.253.140:30447"
databaseConfig:
  timeseriesDB:
    influxDB: disabled
  persistentDB:
    SQLite: enabled
genericFunction: [vo_status, device_status]
periodicFunction:
  check: 1000
  read_property_from_tb2: 5000
consumedVOs:
  tb2:
    url: "http://ngnix-service-td/tb2"
proxy:
  propertiesMap:
    allAvailableResources_tb2: tb2
  actionsMap:
    triggerBringup_tb2: tb2
    mapExport_tb2: tb2
    currentValues_tb2: tb2


