cvo:
  fullnameOverride: cvo
  replicaCount: 1
#  image:
#    repository: new-chart1-repo  # Overridden repository
#    tag: latest

flask-gui:
  fullnameOverride: flask-gui
  replicaCount: 1
#  image:
#    repository: new-chart2-repo  # Overridden repository
#    tag: stable

fxg-zenoh-bridges:
  fullnameOverride: fxg-zenoh-bridges
  replicaCount: 1
  
nginx-td:
  fullnameOverride: nginx-td
  replicaCount: 1

vo1:
  fullnameOverride: vo1
  replicaCount: 1
  
vo2:
  fullnameOverride: vo2
  replicaCount: 1
 
rosbag-drone:
  fullnameOverride: rosbag-drone
  replicaCount: 1
  
rosbag-summit:
  fullnameOverride: rosbag-summit
  replicaCount: 1

liquid-llm:
  fullnameOverride: liquid-llm
  replicaCount: 1


zenoh-helm:
  fullnameOverride: zenoh-helm
  replicaCount: 1
