apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullnameOverride | default .Chart.Name }}
  labels:
    app: {{ .Values.fullnameOverride | default .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.fullnameOverride | default .Chart.Name }}
  ports:
  {{- range .Values.service.ports }}
  - name: {{ .name }}
    port: {{ .port }}
    targetPort: {{ .targetPort }}
    nodePort: {{ .nodePort }}
    protocol: {{ .protocol }}
  {{- end }}

