{{- if eq .Values.voDescriptorOverwrite.bindingNB.sdn.enabled true -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-sdn-controller
  labels:
    app: {{ .Chart.Name }}-sdn-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-sdn-controller
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-sdn-controller
    spec:
      containers:
        - name: {{ .Chart.Name }}-sdn-controller
          image: nepheleproject/nephele-sdiot:latest
          command: ["/home/developer/execute_controller.sh"]
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 1880
          - containerPort: 8992
          - containerPort: 8999
          env:
          - name: JAVA_HOME
            value: "/usr/lib/jvm/java-8-openjdk-amd64/"
          - name: JAVA_TOOL_OPTIONS
            value: "-Dfile.encoding=UTF8"
          resources:
            {{- toYaml .Values.voChartOverwrite.sdn.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-sdn-controller
  labels:
    app: {{ .Chart.Name }}-sdn-controller
spec:
  type: ClusterIP
  ports:
    - port: 1880
      targetPort: 1880
      protocol: TCP
      name: port-1
    - port: 8992
      targetPort: 8992
      protocol: TCP
      name: port-2
    - port: 8999
      targetPort: 8999
      protocol: TCP
      name: port-3
  selector:
    app: {{ .Chart.Name }}-sdn-controller
{{- end }}

