
{{- if eq ((.Values.voDescriptorOverwrite.bindingNB).tsn).enabled true -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-tsn-scheduler
  labels:
    app: {{ .Chart.Name }}-tsn-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-tsn-scheduler
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-tsn-scheduler
    spec:
      containers:
        - name: {{ .Chart.Name }}-tsn-scheduler
          image: nepheleproject/tsn-scheduler:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080
          resources:
            {{- toYaml .Values.voChartOverwrite.tsn.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-tsn-scheduler
  labels:
    app: {{ .Chart.Name }}-tsn-scheduler
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: tsn
  selector:
    app: {{ .Chart.Name }}-tsn-scheduler
{{- end }}

