apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress-vo1
  labels:
    name: nginx-ingress-vo1
spec:
  rules:
    - host: {{ .Values.ingress.nginxHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ngnix-service
                port:
                  number: 80



