fullnameOverride: liquid-llm

# Deployment Settings
replicaCount: 1

image:
  repository: robopaas/liquid_llm
  tag: latest
  pullPolicy: Always

resources:
  requests:
    cpu: "7"
    memory: "15Gi"
  limits:
    cpu: "7"
    memory: "15Gi"

service:
  name: liquid-llm-service
  type: ClusterIP
  port: 80
  targetPort: 80

runtimeClassName: nvidia

command:
  - /run_detection_summit.sh
