{{- range .Values.traefik.routes }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .name }}
  labels:
    {{- include "fxg-zenoh-bridges.labels" $ | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .host }}`) && PathPrefix(`{{ .path }}`)
      kind: Rule
      services:
        - name: {{ $.Values.fullnameOverride }}-service
          port: {{ .port }}
  tls:
    secretName: {{ .tlsSecret }}
{{- end }}

