fullnameOverride: roboflow

# Deployment Settings
replicaCount: 1

image:
  repository: roboflow/roboflow-inference-server-gpu
  tag: latest
  pullPolicy: Always

resources:
  requests:
    cpu: "0.2"
    memory: "2Gi"
  limits:
    cpu: "2"
    memory: "4Gi"

service:
  name: roboflow-service
  type: ClusterIP
  port: 9001
  targetPort: 9001



