apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fullnameOverride | default .Chart.Name }}-deployment
  labels:
    app: zenoh
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      volumes:
        - name: tls-zenoh-config
          configMap:
            name: {{ .Values.volumes.tlsConfigMap }}
            items:
              - key: key.pem
                path: key.pem
              - key: cert.pem
                path: cert.pem
        - name: router-zenoh-config
          configMap:
            name: {{ .Values.volumes.routerConfigMap }}
            items:
              - key: router-conf.json5
                path: router-conf.json5
      containers:
        - name: zenoh
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: RUST_LOG
              value: "zenoh=debug"
          ports:
            {{- range .Values.ports }}
            - containerPort: {{ .port }}
              protocol: {{ .protocol }}
              name: {{ .name }}
            {{- end }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          volumeMounts:
            - name: tls-zenoh-config
              mountPath: /key.pem
              subPath: key.pem
            - name: tls-zenoh-config
              mountPath: /cert.pem
              subPath: cert.pem
            - name: router-zenoh-config
              mountPath: /router-conf.json5
              subPath: router-conf.json5
          args:
            {{- range .Values.args }}
            - "{{ . }}"
            {{- end }}

