apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fullnameOverride | default .Chart.Name }}-deployment
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: zenoh
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: RUST_LOG
              value: "zenoh=debug"
          ports:
            - containerPort: {{ .Values.ports.protocolPort }}
              protocol: {{ .Values.ports.protocol }}
              name: zenoh-protocol
            - containerPort: {{ .Values.ports.apiPort }}
              protocol: {{ .Values.ports.protocol }}
              name: zenoh-api
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          args:
            {{- range .Values.args }}
            - "{{ . }}"
            {{- end }}


