apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullnameOverride }}-service
  labels:
    app: {{ .Release.Name }}
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: zenoh-protocol
      protocol: {{ .Values.ports.protocol }}
      port: {{ .Values.ports.protocolPort }}
      nodePort: {{ .Values.nodePorts.protocolPort }}
    - name: zenoh-api
      protocol: {{ .Values.ports.protocol }}
      port: {{ .Values.ports.apiPort }}
      nodePort: {{ .Values.nodePorts.apiPort }}

