fullnameOverride: zenoh-helm

# Deployment Settings
replicaCount: 1

image:
  repository: eclipse/zenoh
  tag: 1.1.0
  pullPolicy: IfNotPresent

# Ports
ports:
  protocol: TCP
  protocolPort: 7447
  apiPort: 8000

# NodePorts (only numeric values for nodePort)
nodePorts:
  protocolPort: 30447
  apiPort: 30450

# Resources
resources:
  requests:
    cpu: "1"
    memory: 50Mi

# VPA Settings
vpa:
  enabled: true
  minAllowed:
    cpu: 100m
    memory: 50Mi
  maxAllowed:
    cpu: 8
    memory: 30Gi
  controlledResources: ["cpu", "memory"]


args:
  - "--cfg=listen/timeout_ms:1000"
  - "--cfg=listen/exit_on_failure:false"

