fullnameOverride: fxg-zenoh-bridges-vo1
replicaCount: 1

image:
  foxgloveZenohBridge:
    repository: robopaas/foxglove-zenoh-bridges
    tag: demo
    pullPolicy: Always
  foxgloveStudio:
    repository: robopaas/foxglove-studio
    tag: latest
    pullPolicy: Always

resources:
  foxgloveZenohBridge:
    requests:
      memory: "256Mi"
      cpu: "1"
    limits:
      memory: "512Mi"
      cpu: "1"
  foxgloveStudio:
    requests:
      memory: "256Mi"
      cpu: "1"
    limits:
      memory: "512Mi"
      cpu: "1"

env:
  ROS_HOSTNAME: foxglove-zenoh-bridges

service:
  name: foxglove-zenoh-bridges-vo
  type: ClusterIP
  ports:
    fxgWsPort: 8765
    webguiPort: 8080


traefik:
  enabled: true
  routes:
    - name: foxglove-zenoh-bridges-vo-ingress
      host: bridges-vo.nephele-project.ch
      path: /
      port: 8765
      tlsSecret: letsencrypt-cert-production
    - name: foxglove-ingress-vo
      host: foxglove-demo-vo.nephele-project.ch
      path: /
      port: 8080
      tlsSecret: letsencrypt-cert-production
      
      
volumes:
  foxgloveConfig:
    name: foxglove-config-vo
    configMap:
      name: foxglove-demo-vo

